"""Endpoints for the reading loop.

Two surfaces, and they never touch. ``client_router`` is mounted under
``/v1/client`` and guarded by a device token; ``admin_router`` is mounted under
``/v1/admin`` and guarded by the admin credential. Architecture rule 4 says a
device token can never reach an admin capability — the admin surface can
re-ingest, delete and rewrite settings, and a credential able to do that has no
business travelling to a phone.

**This is the first client contract in the project.** Nothing existed under
``/v1/client`` before P2. Sideloaded clients update late, so rule 5 applies from
here on: fields may be added, never removed or given a new meaning.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastapi import APIRouter, Depends, Query, Request
from fastapi.responses import HTMLResponse, Response
from pydantic import BaseModel, Field

from backend.admin.templating import render, require_page_auth
from backend.core import auth, runtime_config
from backend.core.db import get_connection
from backend.core.errors import InvalidRequest
from backend.core.logging import get_logger
from backend.modules.reading import (
    annotate,
    difficulty,
    ingest,
    phrases,
    recompute,
    repository,
    service,
)

log = get_logger("reading.routes")

client_router = APIRouter()
admin_router = APIRouter(dependencies=[Depends(auth.require_admin)])
pages_router = APIRouter()

DeviceId = Annotated[int, Depends(auth.require_device)]


# --------------------------------------------------------------------------- #
# Client surface
# --------------------------------------------------------------------------- #


class ClientEvent(BaseModel):
    """One reported interaction.

    ``idem_key`` is generated by the client, not the server: the client is the
    only party that knows whether this is the same event it failed to upload ten
    minutes ago on a train.
    """

    idem_key: str = Field(min_length=8, max_length=128, description="客户端生成的幂等键")
    type: str = Field(description="事件类型")
    payload: dict[str, Any] = Field(default_factory=dict)
    occurred_at: str | None = Field(default=None, description="客户端时钟，可能不准")


class EventBatch(BaseModel):
    events: list[ClientEvent] = Field(default_factory=list, max_length=500)


@client_router.get("/library", summary="文章清单")
async def library(
    device_id: DeviceId,
    shelf: str = Query("fresh", description="fresh 新备的 / archive 往期 / unread / read / all"),
    source: str | None = Query(None, description="generated / cet4 / cet6 / kaoyan"),
    sort: str | None = Query(None, description="按哪个指标排序，留空则用配置里的默认值"),
    desc: bool = Query(False, description="降序"),
) -> dict[str, Any]:
    """The library.

    There is no ``/today``: deciding what someone should read today needs the
    ability estimate and the selection logic, both of which are P3. The library
    is not a stopgap for that — the intended shape is "a few articles are
    prepared each day, you pick the ones you feel like", which is a list and a
    choice. ``/today`` will be *added* later, which rule 5 permits.
    """
    return service.library(
        auth.learner_for_device(device_id),
        shelf=shelf, source=source,
        # Omitting `sort` means "whatever the console is set to", so the default
        # ordering can be changed without touching a client.
        sort=sort or str(runtime_config.get("library_default_sort")),
        descending=desc,
    )


@client_router.get("/articles/{article_id}", summary="一篇文章的全部内容")
async def article(device_id: DeviceId, article_id: int) -> dict[str, Any]:
    """Text, sentences, every token's analysis, every gloss, and your marks.

    One response, then no further requests while reading. An article still being
    prepared comes back with a ``preparing`` block instead of an error — lazy
    ingest means asking for one is normal, not a mistake.
    """
    return service.article(auth.learner_for_device(device_id), article_id)


@client_router.post("/events", summary="批量上报交互事件")
async def report_events(device_id: DeviceId, batch: EventBatch) -> dict[str, Any]:
    """Accepts duplicates by design — a retry is the protocol working."""
    return service.ingest_events(
        device_id,
        auth.learner_for_device(device_id),
        [event.model_dump() for event in batch.events],
    )


# --------------------------------------------------------------------------- #
# Admin surface
# --------------------------------------------------------------------------- #


@admin_router.get("/reading/stats", summary="阅读模块概览")
async def reading_stats() -> dict[str, Any]:
    return {"stats": repository.stats(), "pending": repository.pending_articles()}


@admin_router.get("/reading/articles", summary="已入库的文章")
async def admin_articles(
    shelf: str = Query("all"),
    source: str | None = Query(None),
    sort: str = Query("composite"),
    desc: bool = Query(False),
) -> dict[str, Any]:
    return {
        "articles": repository.list_articles(shelf=shelf, source=source,
                                             sort=sort, descending=desc),
        "sortable": difficulty.SORTABLE,
    }


@admin_router.get("/reading/papers/{source}", summary="磁盘上的真题，以及入库状态")
async def admin_papers(source: str) -> dict[str, Any]:
    papers = ingest.exam_papers(source)
    return {
        "source": source,
        "total": len(papers),
        "ingested": sum(1 for p in papers if p["ingested"]),
        "papers": papers,
    }


@admin_router.post("/reading/ingest/paper", summary="入库一份真题")
async def admin_ingest_paper(payload: dict[str, Any]) -> dict[str, Any]:
    source = str(payload.get("source") or "")
    ref = str(payload.get("ref") or "")
    if not source or not ref:
        raise InvalidRequest("需要 source 与 ref")
    article_id = ingest.ingest_exam_paper(source, ref)
    job_id = annotate.start_for(article_id)
    return {"article_id": article_id, "job_id": job_id}


@admin_router.post("/reading/ingest/batch", summary="批量预备真题")
async def admin_ingest_batch(payload: dict[str, Any]) -> dict[str, Any]:
    """Prepare many papers at once.

    The same path the lazy per-article ingest uses, run in bulk. This is how the
    remaining 447 papers get done after the annotation format has been checked
    against a few real readings — and doing that unlocks 考频, which is where
    layer ③ of the gloss comes from for free.
    """
    source = str(payload.get("source") or "")
    limit = int(payload.get("limit") or 10)
    papers = [p for p in ingest.exam_papers(source) if not p["ingested"]][:limit]

    ingested: list[int] = []
    for paper in papers:
        try:
            ingested.append(ingest.ingest_exam_paper(source, paper["ref"]))
        except Exception as exc:  # noqa: BLE001 - one bad paper must not stop the batch
            log.warning("paper.ingest.failed", f"{paper['ref']} 入库失败：{exc}",
                        source=source, ref=paper["ref"])

    # One job for the whole lot, not one per paper: the batch machinery — pause,
    # resume, spend cap, recovery from an interrupted run — only applies within
    # a job, and the rate limiter schedules the calls better than a loop can.
    job_id = annotate.start_for_many(ingested, title=f"批量标注 {source} {len(ingested)} 篇")
    return {"source": source, "queued": len(ingested), "job_id": job_id,
            "article_ids": ingested}


@admin_router.post("/reading/ingest/draft/{draft_id}", summary="把生成草稿入库")
async def admin_ingest_draft(draft_id: int) -> dict[str, Any]:
    article_id = ingest.ingest_draft(draft_id)
    return {"article_id": article_id, "job_id": annotate.start_for(article_id)}


@admin_router.post("/reading/articles/{article_id}/annotate", summary="重跑语境标注")
async def admin_reannotate(article_id: int) -> dict[str, Any]:
    return {"job_id": annotate.start_for(article_id, retry_declined=True)}


@admin_router.post("/reading/exam-frequency", summary="按真题标注重算考频")
async def admin_recount_exam_frequency() -> dict[str, Any]:
    """Turn the annotated exam corpus into per-sense exam counts.

    Re-runnable: it zeroes the columns first, so annotating more papers and
    running this again gives the right answer rather than double counting.
    """
    return repository.recount_exam_frequency()


@admin_router.post("/reading/recompute", summary="重算超纲标记与难度画像")
async def admin_recompute() -> dict[str, Any]:
    """Re-derive ``beyond`` and the difficulty profile for every stored article.

    Needed whenever the syllabus rule changes: the rule lives in
    :mod:`...vocabulary.syllabus`, but 453 articles carry the answers whatever
    rule was in force when they were ingested. Only dictionary-derived values
    are rewritten — never a token's identity, offsets, sense or anything a mark
    points at — and the token count is checked before and after.
    """
    return recompute.recompute_all()


@admin_router.post("/reading/phrases/scan", summary="扫描并判断词组")
async def admin_scan_phrases(payload: dict[str, Any] | None = None) -> dict[str, Any]:
    """Find phrase candidates in every ready article, then queue the judgement.

    The finding half is structural and free — it reads tokens that are already
    stored, so retrofitting the whole corpus never touches the expensive sense
    annotation. Only the candidates go to a model.
    """
    ids = (payload or {}).get("article_ids")
    if not ids:
        ids = [r["id"] for r in repository.list_articles(shelf="all", limit=10000)]
    return phrases.scan_and_judge([int(i) for i in ids])


@admin_router.post("/reading/phrases/settle", summary="给落在词组里的 token 打标记")
async def admin_settle_phrases() -> dict[str, Any]:
    """Flag the tokens a confirmed phrase covers, then recount 考频.

    The clean-up the phrase work owes the annotation that came before it: those
    tokens carry a sense chosen without knowing they were half of something
    else, which inflates the exam counts of whichever sense was picked. Runs
    automatically after each judgement batch; exposed here to re-run the whole
    corpus in one go, and because the recount is what makes the correction
    visible.
    """
    flagged = phrases.mark_tokens_in_phrases()
    return {"tokens_flagged": flagged, "exam_frequency": repository.recount_exam_frequency()}


@admin_router.get("/reading/phrases", summary="词组识别概览")
async def admin_phrases(limit: int = Query(40, ge=1, le=500)) -> dict[str, Any]:
    rows = get_connection("learning").execute(
        "SELECT phrase, verdict, COUNT(*) AS n FROM reading_phrases"
        " WHERE verdict IS NOT NULL GROUP BY phrase, verdict ORDER BY n DESC LIMIT ?",
        (limit * 4,),
    ).fetchall()
    return {
        "stats": phrases.stats(),
        "confirmed": [dict(r) for r in rows if r["verdict"] == 1][:limit],
        "rejected": [dict(r) for r in rows if r["verdict"] == 0][:limit],
    }


@admin_router.get("/reading/missing-senses", summary="标注时没有贴合义项的词")
async def admin_missing_senses(limit: int = Query(200, ge=1, le=1000)) -> dict[str, Any]:
    """Words the annotator met and could not fit to any of our senses.

    A free by-product of annotating the exam corpus, and the raw material for
    the 漏义项报告 the sense design asks for: ``around`` in "around 3:30 a.m."
    and ``note`` in "a heavy note of hypocrisy" both turned up on the first run,
    and in both cases the sense set really is missing an entry.

    Words inside a confirmed phrase are left out. ``get up``, ``known as`` and
    ``at least`` were the loudest entries here and none of them was ever a gap
    in a sense set — no sense of ``get`` covers ``get up``. Filtering them is
    what turns this back into a list of things that can actually be fixed.
    """
    rows = repository.declined_tokens(limit)
    by_word: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        by_word.setdefault(row["headword"], []).append(row)
    return {
        "words": len(by_word),
        "occurrences": len(rows),
        "items": [
            {"headword": word, "count": len(items),
             "examples": [{"surface": i["surface"], "sentence": i["sentence"].strip()[:180],
                           "article_id": i["article_id"], "source": i["source"]}
                          for i in items[:3]]}
            for word, items in sorted(by_word.items(), key=lambda kv: -len(kv[1]))
        ],
    }


@admin_router.delete("/reading/articles/{article_id}", summary="删除一篇文章")
async def admin_delete_article(article_id: int) -> dict[str, Any]:
    return {"deleted": repository.delete_article(article_id)}


@admin_router.get("/reading/events", summary="最近的客户端事件")
async def admin_events(limit: int = Query(100, ge=1, le=1000)) -> dict[str, Any]:
    return {"events": repository.recent_events(limit)}


@admin_router.get("/reading/calibration", summary="难度分能否排对三个等级")
async def admin_calibration() -> dict[str, Any]:
    """The acceptance test for the composite score, runnable at any time.

    A weighting that cannot order 四级 < 六级 ≈ 考研 is wrong, whatever it looks
    like — the three exam levels are the one sample in this project with a known
    answer. Exposed as an endpoint rather than a one-off script so that changing
    the weights in the console can be checked immediately.
    """
    # Every article that has been *analysed*, not only the ones that finished
    # annotation: the difficulty indicators come from the local analysis pass,
    # so a paper waiting on the model still has a usable score. Requiring
    # 'ready' here would mean the calibration could not be checked until an
    # entire corpus had been through the annotator.
    per_source = repository.scores_by_source()

    def median(values: list[float]) -> float | None:
        if not values:
            return None
        ordered = sorted(values)
        middle = len(ordered) // 2
        if len(ordered) % 2:
            return round(ordered[middle], 1)
        return round((ordered[middle - 1] + ordered[middle]) / 2, 1)

    medians = {source: median(values) for source, values in per_source.items()}
    four, six, ky = medians.get("cet4"), medians.get("cet6"), medians.get("kaoyan")
    ordered = None
    if four is not None and six is not None and ky is not None:
        ordered = four < six and four < ky

    return {
        "weights": difficulty.weights(),
        "counts": {source: len(values) for source, values in per_source.items()},
        "medians": medians,
        "ordered_correctly": ordered,
        "note": "四级应低于六级与考研；六级与考研实测接近，考研略高。排不对说明权重或指标有问题。",
    }


# --------------------------------------------------------------------------- #
# Pages
# --------------------------------------------------------------------------- #

WEB_READER_DEVICE = "web-reader"


def _web_reader_token() -> str:
    """A device token for the development reading page.

    The page could have used the admin session it is already served under, but
    then it would not be exercising the client contract at all — and the client
    contract is the thing P2 exists to get right. So it registers itself as a
    device like any other and talks to ``/v1/client`` over a bearer token.
    """
    token = runtime_config.get("reading_web_token")
    if token:
        return str(token)
    issued = auth.create_device(WEB_READER_DEVICE)
    runtime_config.set("reading_web_token", issued)
    return issued


@pages_router.get("/admin/reading", response_class=HTMLResponse)
async def reading_page(request: Request) -> Response:
    if (redirect := require_page_auth(request)) is not None:
        return redirect
    return render(
        request,
        "reading.html",
        stats=repository.stats(),
        pending=repository.pending_articles(),
        articles=repository.list_articles(shelf="all", sort="prepared_at", descending=True,
                                          limit=200),
        sortable=difficulty.SORTABLE,
        sources=repository.SOURCE_LABELS,
    )


@pages_router.get("/admin/reader", response_class=HTMLResponse)
async def reader_index(request: Request) -> Response:
    if (redirect := require_page_auth(request)) is not None:
        return redirect
    return render(request, "reader.html", token=_web_reader_token(), article_id=0,
                  progress_seconds=int(runtime_config.get("progress_report_seconds")))


@pages_router.get("/admin/reader/{article_id}", response_class=HTMLResponse)
async def reader_page(request: Request, article_id: int) -> Response:
    if (redirect := require_page_auth(request)) is not None:
        return redirect
    return render(request, "reader.html", token=_web_reader_token(), article_id=article_id,
                  progress_seconds=int(runtime_config.get("progress_report_seconds")))
