"""Dictionary schema.

All of this lives in ``dictionary.db``: reference data imported from ECDICT,
rebuildable at any time, deliberately kept out of the file that gets backed up.

P0 also created empty ``senses`` and ``word_families`` tables here as
placeholders. P1b moved them to ``content.db`` and migration 3 drops them: they
are generated by a model, so re-running the import script would have destroyed
work that cost money — which is precisely the distinction the two databases
exist to make.

``phrases`` (migration 4) is the same import file read a second time, for the
rows the first pass threw away.

Term mapping for the design documents:
    headword    词条        the lemma a surface form resolves to
    phrase      词组        a multi-word dictionary entry
    sense       义项        one *English concept*, not one Chinese translation
    word family 词族        root plus its derivations
"""

from __future__ import annotations

from backend.core.db import Migration

MIGRATIONS = [
    Migration(
        version=1,
        name="dictionary entries",
        database="dictionary",
        apply="""
        -- One row per headword, imported from ECDICT.
        CREATE TABLE IF NOT EXISTS words (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            headword    TEXT    NOT NULL UNIQUE,
            phonetic    TEXT,
            -- ECDICT's English definition. Not the same thing as a sense's
            -- concept definition: this is dictionary prose, senses are ours.
            definition  TEXT,
            -- Chinese, comma-piled. Layer 2 of the three-layer gloss.
            translation TEXT,
            pos_hint    TEXT,
            collins     INTEGER,
            oxford      INTEGER,
            -- Syllabus tags: zk / gk / cet4 / cet6 / ky / toefl / ielts / gre
            tags        TEXT,
            -- Frequency ranks. Lower is more common; these are the difficulty
            -- prior the ability model will build on in P3.
            bnc         INTEGER,
            frq         INTEGER,
            -- ECDICT inflection field, kept verbatim for cross-checking lemmas.
            exchange    TEXT
        );
        CREATE INDEX IF NOT EXISTS idx_words_headword ON words (headword);
        CREATE INDEX IF NOT EXISTS idx_words_bnc      ON words (bnc);
        CREATE INDEX IF NOT EXISTS idx_words_frq      ON words (frq);
        CREATE INDEX IF NOT EXISTS idx_words_tags     ON words (tags);

        -- Surface form -> headword, expanded from the exchange field at import.
        -- Used to cross-check the NLP lemmatiser and to catch forms it misses;
        -- it cannot disambiguate on its own (left -> leave or left?), which is
        -- exactly why part-of-speech tagging carries the main load.
        CREATE TABLE IF NOT EXISTS word_forms (
            surface   TEXT NOT NULL,
            headword  TEXT NOT NULL,
            kind      TEXT,
            PRIMARY KEY (surface, headword)
        );
        CREATE INDEX IF NOT EXISTS idx_word_forms_surface ON word_forms (surface);
        """,
    ),
    Migration(
        version=4,
        name="multi-word entries",
        database="dictionary",
        # Kept apart from `words` on purpose. The import deliberately dropped
        # every multi-word entry ("Multi-word entries are phrases, not
        # headwords"), which was right while phrases were out of scope — and it
        # threw away 366,502 rows that already carry Chinese glosses for
        # `get up`, `account for`, `look after` and the rest.
        #
        # **Why this splits where the study record merged.** Same test, opposite
        # answer: is there a query that needs both types at once? Review
        # scheduling orders words and phrases into one list, so those merged.
        # Looking a thing up is always either a word or a phrase, so these
        # split — and `words` stays at 404,011 rows instead of 722,218, which
        # matters because it is the reading path and one article hits it
        # hundreds of times.
        #
        # No quality signal exists here: 318k of these are two-to-four-word
        # sequences, only six carry a syllabus tag, and frequency is zero
        # throughout. This table answers "does this combination have a
        # dictionary entry", nothing more. Whether an occurrence *is* a phrase
        # is decided per occurrence, in context.
        apply="""
        CREATE TABLE IF NOT EXISTS phrases (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            phrase      TEXT    NOT NULL UNIQUE,
            -- Number of words, so the matcher can try longest-first.
            word_count  INTEGER NOT NULL,
            -- First word, for the index the matcher actually uses: candidates
            -- are found by looking up the verb's lemma, not the whole string.
            head        TEXT    NOT NULL,
            translation TEXT,
            definition  TEXT,
            collins     INTEGER,
            oxford      INTEGER
        );
        CREATE INDEX IF NOT EXISTS idx_phrases_head ON phrases (head, word_count);
        """,
    ),
    Migration(
        version=3,
        name="move senses and word families out of the dictionary",
        database="dictionary",
        # P0 put these here as placeholders. P1b moved them to content.db,
        # because they are generated by a model and cost money to rebuild, while
        # this database is defined as disposable and is never backed up —
        # `import_dictionary.py` would have wiped them. They were still empty
        # when they moved, so there is nothing to migrate, only to remove.
        apply="""
        DROP TABLE IF EXISTS senses;
        DROP TABLE IF EXISTS word_families;
        """,
    ),
    Migration(
        version=2,
        name="sense and word family structure (superseded by v3)",
        database="dictionary",
        apply="""
        -- A sense is one English concept. Chinese glosses are its projections,
        -- which is why concept_en is the identity column and gloss_zh is not.
        -- Granularity: medium, split on concept boundaries, never on
        -- differences that exist only in Chinese translation.
        CREATE TABLE IF NOT EXISTS senses (
            id             INTEGER PRIMARY KEY AUTOINCREMENT,
            word_id        INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
            ordinal        INTEGER NOT NULL,
            concept_en     TEXT    NOT NULL,
            gloss_zh       TEXT    NOT NULL,
            -- Written with words the learner already knows, so reading a
            -- definition never introduces new unknowns. Regenerated as their
            -- level rises.
            simple_def_en  TEXT,
            -- Populated from exam corpus statistics in P1: how often this sense
            -- actually appears in past papers, which outranks any word list.
            exam_frequency INTEGER NOT NULL DEFAULT 0,
            is_exam_key    INTEGER NOT NULL DEFAULT 0,
            created_at     TEXT,
            UNIQUE (word_id, ordinal)
        );
        CREATE INDEX IF NOT EXISTS idx_senses_word ON senses (word_id);

        -- Root -> derivation, with the breakdown shown when a derived word is
        -- met and its root is already known (nationality <- nation + -ity).
        CREATE TABLE IF NOT EXISTS word_families (
            id             INTEGER PRIMARY KEY AUTOINCREMENT,
            root_word_id   INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
            member_word_id INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
            affix          TEXT,
            breakdown_zh   TEXT,
            UNIQUE (root_word_id, member_word_id)
        );
        CREATE INDEX IF NOT EXISTS idx_family_member ON word_families (member_word_id);
        """,
    ),
]
