// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// 文章清单
    ///
    /// The library.
    ///
    /// There is no ``/today``: deciding what someone should read today needs the
    /// ability estimate and the selection logic, both of which are P3. The library
    /// is not a stopgap for that — the intended shape is "a few articles are
    /// prepared each day, you pick the ones you feel like", which is a list and a
    /// choice. ``/today`` will be *added* later, which rule 5 permits.
    ///
    /// - Remark: HTTP `GET /v1/client/library`.
    /// - Remark: Generated from `#/paths//v1/client/library/get(library_v1_client_library_get)`.
    public enum library_v1_client_library_get {
        public static let id: Swift.String = "library_v1_client_library_get"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/library/GET/query`.
            public struct Query: Sendable, Hashable {
                /// fresh 新备的 / archive 往期 / unread / read / all
                ///
                /// - Remark: Generated from `#/paths/v1/client/library/GET/query/shelf`.
                public var shelf: Swift.String?
                /// generated / cet4 / cet6 / kaoyan
                ///
                /// - Remark: Generated from `#/paths/v1/client/library/GET/query/source`.
                public var source: Swift.String?
                /// 按哪个指标排序，留空则用配置里的默认值
                ///
                /// - Remark: Generated from `#/paths/v1/client/library/GET/query/sort`.
                public var sort: Swift.String?
                /// 降序
                ///
                /// - Remark: Generated from `#/paths/v1/client/library/GET/query/desc`.
                public var desc: Swift.Bool?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - shelf: fresh 新备的 / archive 往期 / unread / read / all
                ///   - source: generated / cet4 / cet6 / kaoyan
                ///   - sort: 按哪个指标排序，留空则用配置里的默认值
                ///   - desc: 降序
                public init(
                    shelf: Swift.String? = nil,
                    source: Swift.String? = nil,
                    sort: Swift.String? = nil,
                    desc: Swift.Bool? = nil
                ) {
                    self.shelf = shelf
                    self.source = source
                    self.sort = sort
                    self.desc = desc
                }
            }
            public var query: Operations.library_v1_client_library_get.Input.Query
            /// - Remark: Generated from `#/paths/v1/client/library/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.library_v1_client_library_get.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.library_v1_client_library_get.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.library_v1_client_library_get.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            public init(
                query: Operations.library_v1_client_library_get.Input.Query = .init(),
                headers: Operations.library_v1_client_library_get.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/library/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/library/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.LibraryResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.LibraryResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.library_v1_client_library_get.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.library_v1_client_library_get.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/library/get(library_v1_client_library_get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.library_v1_client_library_get.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.library_v1_client_library_get.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/library/GET/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/library/GET/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.library_v1_client_library_get.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.library_v1_client_library_get.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/library/get(library_v1_client_library_get)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.library_v1_client_library_get.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.library_v1_client_library_get.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 一篇文章的全部内容
    ///
    /// Text, sentences, every token's analysis, every gloss, and your marks.
    ///
    /// One response, then no further requests while reading. An article still being
    /// prepared comes back with a ``preparing`` block instead of an error — lazy
    /// ingest means asking for one is normal, not a mistake.
    ///
    /// - Remark: HTTP `GET /v1/client/articles/{article_id}`.
    /// - Remark: Generated from `#/paths//v1/client/articles/{article_id}/get(article_v1_client_articles__article_id__get)`.
    public enum article_v1_client_articles__article_id__get {
        public static let id: Swift.String = "article_v1_client_articles__article_id__get"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/articles/{article_id}/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/articles/{article_id}/GET/path/article_id`.
                public var article_id: Swift.Int
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - article_id:
                public init(article_id: Swift.Int) {
                    self.article_id = article_id
                }
            }
            public var path: Operations.article_v1_client_articles__article_id__get.Input.Path
            /// - Remark: Generated from `#/paths/v1/client/articles/{article_id}/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.article_v1_client_articles__article_id__get.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.article_v1_client_articles__article_id__get.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.article_v1_client_articles__article_id__get.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.article_v1_client_articles__article_id__get.Input.Path,
                headers: Operations.article_v1_client_articles__article_id__get.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/articles/{article_id}/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/articles/{article_id}/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.ArticleResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.ArticleResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.article_v1_client_articles__article_id__get.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.article_v1_client_articles__article_id__get.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/articles/{article_id}/get(article_v1_client_articles__article_id__get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.article_v1_client_articles__article_id__get.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.article_v1_client_articles__article_id__get.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/articles/{article_id}/GET/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/articles/{article_id}/GET/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.article_v1_client_articles__article_id__get.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.article_v1_client_articles__article_id__get.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/articles/{article_id}/get(article_v1_client_articles__article_id__get)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.article_v1_client_articles__article_id__get.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.article_v1_client_articles__article_id__get.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 批量上报交互事件
    ///
    /// Accepts duplicates by design — a retry is the protocol working.
    ///
    /// - Remark: HTTP `POST /v1/client/events`.
    /// - Remark: Generated from `#/paths//v1/client/events/post(report_events_v1_client_events_post)`.
    public enum report_events_v1_client_events_post {
        public static let id: Swift.String = "report_events_v1_client_events_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/events/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_events_v1_client_events_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_events_v1_client_events_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.report_events_v1_client_events_post.Input.Headers
            /// - Remark: Generated from `#/paths/v1/client/events/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/events/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.EventBatch)
            }
            public var body: Operations.report_events_v1_client_events_post.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.report_events_v1_client_events_post.Input.Headers = .init(),
                body: Operations.report_events_v1_client_events_post.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/events/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/events/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.EventBatchResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.EventBatchResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_events_v1_client_events_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_events_v1_client_events_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/events/post(report_events_v1_client_events_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.report_events_v1_client_events_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.report_events_v1_client_events_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/events/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/events/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_events_v1_client_events_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_events_v1_client_events_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/events/post(report_events_v1_client_events_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.report_events_v1_client_events_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.report_events_v1_client_events_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 今天要复习的全部内容
    ///
    /// - Remark: HTTP `GET /v1/client/reviews`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/get(reviews_v1_client_reviews_get)`.
    public enum reviews_v1_client_reviews_get {
        public static let id: Swift.String = "reviews_v1_client_reviews_get"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/reviews/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.reviews_v1_client_reviews_get.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.reviews_v1_client_reviews_get.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.reviews_v1_client_reviews_get.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.reviews_v1_client_reviews_get.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.ReviewDayResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.ReviewDayResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.reviews_v1_client_reviews_get.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.reviews_v1_client_reviews_get.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/get(reviews_v1_client_reviews_get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.reviews_v1_client_reviews_get.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.reviews_v1_client_reviews_get.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/GET/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/GET/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.reviews_v1_client_reviews_get.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.reviews_v1_client_reviews_get.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/get(reviews_v1_client_reviews_get)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.reviews_v1_client_reviews_get.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.reviews_v1_client_reviews_get.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 上报一次作答
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/answer`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/answer/post(report_answer_v1_client_reviews_answer_post)`.
    public enum report_answer_v1_client_reviews_answer_post {
        public static let id: Swift.String = "report_answer_v1_client_reviews_answer_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/reviews/answer/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_answer_v1_client_reviews_answer_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_answer_v1_client_reviews_answer_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.report_answer_v1_client_reviews_answer_post.Input.Headers
            /// - Remark: Generated from `#/paths/v1/client/reviews/answer/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/answer/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.AnswerIn)
            }
            public var body: Operations.report_answer_v1_client_reviews_answer_post.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.report_answer_v1_client_reviews_answer_post.Input.Headers = .init(),
                body: Operations.report_answer_v1_client_reviews_answer_post.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/answer/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/answer/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.AnswerResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.AnswerResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_answer_v1_client_reviews_answer_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_answer_v1_client_reviews_answer_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/answer/post(report_answer_v1_client_reviews_answer_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.report_answer_v1_client_reviews_answer_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.report_answer_v1_client_reviews_answer_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/answer/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/answer/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_answer_v1_client_reviews_answer_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_answer_v1_client_reviews_answer_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/answer/post(report_answer_v1_client_reviews_answer_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.report_answer_v1_client_reviews_answer_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.report_answer_v1_client_reviews_answer_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 批量上报作答（离线补报用）
    ///
    /// Replay a day's answers in order, skipping anything already recorded.
    ///
    /// **Why this exists at all.** ``/reviews`` has always been offline-shaped —
    /// every card ships with its sentences — but the answer path was one online
    /// POST per question with no key and no queue, so review failed on every
    /// question without a connection while reading carried on fine. That broke
    /// 架构铁律 2 for half the product, and 读后抽查 being dropped left review as
    /// the only place the learner produces anything.
    ///
    /// **Order matters and is the client's.** A review session is a state machine:
    /// passing 看词想义 unlocks 看义想词, failing it locks it again. So the batch is
    /// applied in the order given, not concurrently, and a failure in the middle
    /// stops nothing — the remaining answers still apply, and the one that failed
    /// is reported with its key so the client can decide.
    ///
    /// The single-answer endpoint stays exactly as it was. 架构铁律 5 is only
    /// additive, and a client written against it keeps working untouched.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/answers`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/answers/post(report_answers_v1_client_reviews_answers_post)`.
    public enum report_answers_v1_client_reviews_answers_post {
        public static let id: Swift.String = "report_answers_v1_client_reviews_answers_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/reviews/answers/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_answers_v1_client_reviews_answers_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_answers_v1_client_reviews_answers_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.report_answers_v1_client_reviews_answers_post.Input.Headers
            /// - Remark: Generated from `#/paths/v1/client/reviews/answers/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/answers/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.AnswersIn)
            }
            public var body: Operations.report_answers_v1_client_reviews_answers_post.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.report_answers_v1_client_reviews_answers_post.Input.Headers = .init(),
                body: Operations.report_answers_v1_client_reviews_answers_post.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/answers/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/answers/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.AnswersResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.AnswersResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_answers_v1_client_reviews_answers_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_answers_v1_client_reviews_answers_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/answers/post(report_answers_v1_client_reviews_answers_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.report_answers_v1_client_reviews_answers_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.report_answers_v1_client_reviews_answers_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/answers/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/answers/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_answers_v1_client_reviews_answers_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_answers_v1_client_reviews_answers_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/answers/post(report_answers_v1_client_reviews_answers_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.report_answers_v1_client_reviews_answers_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.report_answers_v1_client_reviews_answers_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 上报一次拼写
    ///
    /// Recorded, never scheduled on.
    ///
    /// 决定 13 keeps spelling out of the scheduler entirely: it is an optional
    /// reinforcement, and letting it move due dates would mix a productive-recall
    /// difficulty into a recognition track. What is stored is what was typed, not
    /// just whether it was right — that is the whole value of the record.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/spelling`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/spelling/post(report_spelling_v1_client_reviews_spelling_post)`.
    public enum report_spelling_v1_client_reviews_spelling_post {
        public static let id: Swift.String = "report_spelling_v1_client_reviews_spelling_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/reviews/spelling/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_spelling_v1_client_reviews_spelling_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_spelling_v1_client_reviews_spelling_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.report_spelling_v1_client_reviews_spelling_post.Input.Headers
            /// - Remark: Generated from `#/paths/v1/client/reviews/spelling/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/spelling/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.SpellingIn)
            }
            public var body: Operations.report_spelling_v1_client_reviews_spelling_post.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.report_spelling_v1_client_reviews_spelling_post.Input.Headers = .init(),
                body: Operations.report_spelling_v1_client_reviews_spelling_post.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/spelling/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/spelling/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.SpellingResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.SpellingResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_spelling_v1_client_reviews_spelling_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_spelling_v1_client_reviews_spelling_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/spelling/post(report_spelling_v1_client_reviews_spelling_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.report_spelling_v1_client_reviews_spelling_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.report_spelling_v1_client_reviews_spelling_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/spelling/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/spelling/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_spelling_v1_client_reviews_spelling_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_spelling_v1_client_reviews_spelling_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/spelling/post(report_spelling_v1_client_reviews_spelling_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.report_spelling_v1_client_reviews_spelling_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.report_spelling_v1_client_reviews_spelling_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 批量上报拼写（离线补报用）
    ///
    /// The offline path for spelling, which P4 gave answers and not this.
    ///
    /// 決定 12 of P4 added a batch endpoint for answers because "地铁里每答一题都
    /// 失败" broke 架构前提 2 for half the product. Spelling was out of scope that
    /// day and kept its one-at-a-time online POST, so the last step of the day was
    /// still the one step that needed a network. Same store, same idempotency key,
    /// same per-item verdict as the answers batch — a client that already speaks
    /// that one needs no new vocabulary here.
    ///
    /// **Order does not matter here**, unlike answers: each attempt is an
    /// independent record, and spelling never touches the scheduler (决定 13). They
    /// are applied in the order given anyway, because replaying in sequence is
    /// what the client's outbox does.
    ///
    /// Re-applying an attempt whose first try failed writes a second row in
    /// `spelling_attempts`. That is a duplicate record rather than a wrong one —
    /// nothing reads the table to make a decision — and the alternative is the
    /// attempt being silently dropped.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/spellings`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/spellings/post(report_spellings_v1_client_reviews_spellings_post)`.
    public enum report_spellings_v1_client_reviews_spellings_post {
        public static let id: Swift.String = "report_spellings_v1_client_reviews_spellings_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/reviews/spellings/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_spellings_v1_client_reviews_spellings_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.report_spellings_v1_client_reviews_spellings_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.report_spellings_v1_client_reviews_spellings_post.Input.Headers
            /// - Remark: Generated from `#/paths/v1/client/reviews/spellings/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/spellings/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.SpellingsIn)
            }
            public var body: Operations.report_spellings_v1_client_reviews_spellings_post.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.report_spellings_v1_client_reviews_spellings_post.Input.Headers = .init(),
                body: Operations.report_spellings_v1_client_reviews_spellings_post.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/spellings/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/spellings/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.SpellingsResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.SpellingsResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_spellings_v1_client_reviews_spellings_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_spellings_v1_client_reviews_spellings_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/spellings/post(report_spellings_v1_client_reviews_spellings_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.report_spellings_v1_client_reviews_spellings_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.report_spellings_v1_client_reviews_spellings_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/reviews/spellings/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/reviews/spellings/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.report_spellings_v1_client_reviews_spellings_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.report_spellings_v1_client_reviews_spellings_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/reviews/spellings/post(report_spellings_v1_client_reviews_spellings_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.report_spellings_v1_client_reviews_spellings_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.report_spellings_v1_client_reviews_spellings_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// 今日包：当天的文章与复习，一次拿全
    ///
    /// One response the client can work from all day without a network.
    ///
    /// New endpoint rather than fields added to an existing one — 架构铁律 5 lets
    /// us add, never change, and P2 deliberately left this shape unguessed
    /// (`phase-2.html` §6) rather than bolting an invented one onto `/articles`.
    ///
    /// **Does not include exam papers** (决定 9). They have their own entrance at
    /// ``/v1/client/library?source=cet4|cet6|kaoyan``. The response says so in
    /// ``excludes_exam_papers`` so a client cannot conclude otherwise by accident.
    ///
    /// - Remark: HTTP `GET /v1/client/today`.
    /// - Remark: Generated from `#/paths//v1/client/today/get(today_v1_client_today_get)`.
    public enum today_v1_client_today_get {
        public static let id: Swift.String = "today_v1_client_today_get"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v1/client/today/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.today_v1_client_today_get.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.today_v1_client_today_get.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.today_v1_client_today_get.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.today_v1_client_today_get.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/today/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/today/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.TodayResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.TodayResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.today_v1_client_today_get.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.today_v1_client_today_get.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//v1/client/today/get(today_v1_client_today_get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.today_v1_client_today_get.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.today_v1_client_today_get.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v1/client/today/GET/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v1/client/today/GET/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.today_v1_client_today_get.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.today_v1_client_today_get.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//v1/client/today/get(today_v1_client_today_get)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.today_v1_client_today_get.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.today_v1_client_today_get.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
