// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// 文章清单
    ///
    /// The library.
    ///
    /// There is no ``/today``: deciding what someone should read today needs the
    /// ability estimate and the selection logic, both of which are P3. The library
    /// is not a stopgap for that — the intended shape is "a few articles are
    /// prepared each day, you pick the ones you feel like", which is a list and a
    /// choice. ``/today`` will be *added* later, which rule 5 permits.
    ///
    /// - Remark: HTTP `GET /v1/client/library`.
    /// - Remark: Generated from `#/paths//v1/client/library/get(library_v1_client_library_get)`.
    func library_v1_client_library_get(_ input: Operations.library_v1_client_library_get.Input) async throws -> Operations.library_v1_client_library_get.Output
    /// 一篇文章的全部内容
    ///
    /// Text, sentences, every token's analysis, every gloss, and your marks.
    ///
    /// One response, then no further requests while reading. An article still being
    /// prepared comes back with a ``preparing`` block instead of an error — lazy
    /// ingest means asking for one is normal, not a mistake.
    ///
    /// - Remark: HTTP `GET /v1/client/articles/{article_id}`.
    /// - Remark: Generated from `#/paths//v1/client/articles/{article_id}/get(article_v1_client_articles__article_id__get)`.
    func article_v1_client_articles__article_id__get(_ input: Operations.article_v1_client_articles__article_id__get.Input) async throws -> Operations.article_v1_client_articles__article_id__get.Output
    /// 批量上报交互事件
    ///
    /// Accepts duplicates by design — a retry is the protocol working.
    ///
    /// - Remark: HTTP `POST /v1/client/events`.
    /// - Remark: Generated from `#/paths//v1/client/events/post(report_events_v1_client_events_post)`.
    func report_events_v1_client_events_post(_ input: Operations.report_events_v1_client_events_post.Input) async throws -> Operations.report_events_v1_client_events_post.Output
    /// 今天要复习的全部内容
    ///
    /// - Remark: HTTP `GET /v1/client/reviews`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/get(reviews_v1_client_reviews_get)`.
    func reviews_v1_client_reviews_get(_ input: Operations.reviews_v1_client_reviews_get.Input) async throws -> Operations.reviews_v1_client_reviews_get.Output
    /// 上报一次作答
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/answer`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/answer/post(report_answer_v1_client_reviews_answer_post)`.
    func report_answer_v1_client_reviews_answer_post(_ input: Operations.report_answer_v1_client_reviews_answer_post.Input) async throws -> Operations.report_answer_v1_client_reviews_answer_post.Output
    /// 批量上报作答（离线补报用）
    ///
    /// Replay a day's answers in order, skipping anything already recorded.
    ///
    /// **Why this exists at all.** ``/reviews`` has always been offline-shaped —
    /// every card ships with its sentences — but the answer path was one online
    /// POST per question with no key and no queue, so review failed on every
    /// question without a connection while reading carried on fine. That broke
    /// 架构铁律 2 for half the product, and 读后抽查 being dropped left review as
    /// the only place the learner produces anything.
    ///
    /// **Order matters and is the client's.** A review session is a state machine:
    /// passing 看词想义 unlocks 看义想词, failing it locks it again. So the batch is
    /// applied in the order given, not concurrently, and a failure in the middle
    /// stops nothing — the remaining answers still apply, and the one that failed
    /// is reported with its key so the client can decide.
    ///
    /// The single-answer endpoint stays exactly as it was. 架构铁律 5 is only
    /// additive, and a client written against it keeps working untouched.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/answers`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/answers/post(report_answers_v1_client_reviews_answers_post)`.
    func report_answers_v1_client_reviews_answers_post(_ input: Operations.report_answers_v1_client_reviews_answers_post.Input) async throws -> Operations.report_answers_v1_client_reviews_answers_post.Output
    /// 上报一次拼写
    ///
    /// Recorded, never scheduled on.
    ///
    /// 决定 13 keeps spelling out of the scheduler entirely: it is an optional
    /// reinforcement, and letting it move due dates would mix a productive-recall
    /// difficulty into a recognition track. What is stored is what was typed, not
    /// just whether it was right — that is the whole value of the record.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/spelling`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/spelling/post(report_spelling_v1_client_reviews_spelling_post)`.
    func report_spelling_v1_client_reviews_spelling_post(_ input: Operations.report_spelling_v1_client_reviews_spelling_post.Input) async throws -> Operations.report_spelling_v1_client_reviews_spelling_post.Output
    /// 批量上报拼写（离线补报用）
    ///
    /// The offline path for spelling, which P4 gave answers and not this.
    ///
    /// 決定 12 of P4 added a batch endpoint for answers because "地铁里每答一题都
    /// 失败" broke 架构前提 2 for half the product. Spelling was out of scope that
    /// day and kept its one-at-a-time online POST, so the last step of the day was
    /// still the one step that needed a network. Same store, same idempotency key,
    /// same per-item verdict as the answers batch — a client that already speaks
    /// that one needs no new vocabulary here.
    ///
    /// **Order does not matter here**, unlike answers: each attempt is an
    /// independent record, and spelling never touches the scheduler (决定 13). They
    /// are applied in the order given anyway, because replaying in sequence is
    /// what the client's outbox does.
    ///
    /// Re-applying an attempt whose first try failed writes a second row in
    /// `spelling_attempts`. That is a duplicate record rather than a wrong one —
    /// nothing reads the table to make a decision — and the alternative is the
    /// attempt being silently dropped.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/spellings`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/spellings/post(report_spellings_v1_client_reviews_spellings_post)`.
    func report_spellings_v1_client_reviews_spellings_post(_ input: Operations.report_spellings_v1_client_reviews_spellings_post.Input) async throws -> Operations.report_spellings_v1_client_reviews_spellings_post.Output
    /// 今日包：当天的文章与复习，一次拿全
    ///
    /// One response the client can work from all day without a network.
    ///
    /// New endpoint rather than fields added to an existing one — 架构铁律 5 lets
    /// us add, never change, and P2 deliberately left this shape unguessed
    /// (`phase-2.html` §6) rather than bolting an invented one onto `/articles`.
    ///
    /// **Does not include exam papers** (决定 9). They have their own entrance at
    /// ``/v1/client/library?source=cet4|cet6|kaoyan``. The response says so in
    /// ``excludes_exam_papers`` so a client cannot conclude otherwise by accident.
    ///
    /// - Remark: HTTP `GET /v1/client/today`.
    /// - Remark: Generated from `#/paths//v1/client/today/get(today_v1_client_today_get)`.
    func today_v1_client_today_get(_ input: Operations.today_v1_client_today_get.Input) async throws -> Operations.today_v1_client_today_get.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// 文章清单
    ///
    /// The library.
    ///
    /// There is no ``/today``: deciding what someone should read today needs the
    /// ability estimate and the selection logic, both of which are P3. The library
    /// is not a stopgap for that — the intended shape is "a few articles are
    /// prepared each day, you pick the ones you feel like", which is a list and a
    /// choice. ``/today`` will be *added* later, which rule 5 permits.
    ///
    /// - Remark: HTTP `GET /v1/client/library`.
    /// - Remark: Generated from `#/paths//v1/client/library/get(library_v1_client_library_get)`.
    public func library_v1_client_library_get(
        query: Operations.library_v1_client_library_get.Input.Query = .init(),
        headers: Operations.library_v1_client_library_get.Input.Headers = .init()
    ) async throws -> Operations.library_v1_client_library_get.Output {
        try await library_v1_client_library_get(Operations.library_v1_client_library_get.Input(
            query: query,
            headers: headers
        ))
    }
    /// 一篇文章的全部内容
    ///
    /// Text, sentences, every token's analysis, every gloss, and your marks.
    ///
    /// One response, then no further requests while reading. An article still being
    /// prepared comes back with a ``preparing`` block instead of an error — lazy
    /// ingest means asking for one is normal, not a mistake.
    ///
    /// - Remark: HTTP `GET /v1/client/articles/{article_id}`.
    /// - Remark: Generated from `#/paths//v1/client/articles/{article_id}/get(article_v1_client_articles__article_id__get)`.
    public func article_v1_client_articles__article_id__get(
        path: Operations.article_v1_client_articles__article_id__get.Input.Path,
        headers: Operations.article_v1_client_articles__article_id__get.Input.Headers = .init()
    ) async throws -> Operations.article_v1_client_articles__article_id__get.Output {
        try await article_v1_client_articles__article_id__get(Operations.article_v1_client_articles__article_id__get.Input(
            path: path,
            headers: headers
        ))
    }
    /// 批量上报交互事件
    ///
    /// Accepts duplicates by design — a retry is the protocol working.
    ///
    /// - Remark: HTTP `POST /v1/client/events`.
    /// - Remark: Generated from `#/paths//v1/client/events/post(report_events_v1_client_events_post)`.
    public func report_events_v1_client_events_post(
        headers: Operations.report_events_v1_client_events_post.Input.Headers = .init(),
        body: Operations.report_events_v1_client_events_post.Input.Body
    ) async throws -> Operations.report_events_v1_client_events_post.Output {
        try await report_events_v1_client_events_post(Operations.report_events_v1_client_events_post.Input(
            headers: headers,
            body: body
        ))
    }
    /// 今天要复习的全部内容
    ///
    /// - Remark: HTTP `GET /v1/client/reviews`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/get(reviews_v1_client_reviews_get)`.
    public func reviews_v1_client_reviews_get(headers: Operations.reviews_v1_client_reviews_get.Input.Headers = .init()) async throws -> Operations.reviews_v1_client_reviews_get.Output {
        try await reviews_v1_client_reviews_get(Operations.reviews_v1_client_reviews_get.Input(headers: headers))
    }
    /// 上报一次作答
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/answer`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/answer/post(report_answer_v1_client_reviews_answer_post)`.
    public func report_answer_v1_client_reviews_answer_post(
        headers: Operations.report_answer_v1_client_reviews_answer_post.Input.Headers = .init(),
        body: Operations.report_answer_v1_client_reviews_answer_post.Input.Body
    ) async throws -> Operations.report_answer_v1_client_reviews_answer_post.Output {
        try await report_answer_v1_client_reviews_answer_post(Operations.report_answer_v1_client_reviews_answer_post.Input(
            headers: headers,
            body: body
        ))
    }
    /// 批量上报作答（离线补报用）
    ///
    /// Replay a day's answers in order, skipping anything already recorded.
    ///
    /// **Why this exists at all.** ``/reviews`` has always been offline-shaped —
    /// every card ships with its sentences — but the answer path was one online
    /// POST per question with no key and no queue, so review failed on every
    /// question without a connection while reading carried on fine. That broke
    /// 架构铁律 2 for half the product, and 读后抽查 being dropped left review as
    /// the only place the learner produces anything.
    ///
    /// **Order matters and is the client's.** A review session is a state machine:
    /// passing 看词想义 unlocks 看义想词, failing it locks it again. So the batch is
    /// applied in the order given, not concurrently, and a failure in the middle
    /// stops nothing — the remaining answers still apply, and the one that failed
    /// is reported with its key so the client can decide.
    ///
    /// The single-answer endpoint stays exactly as it was. 架构铁律 5 is only
    /// additive, and a client written against it keeps working untouched.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/answers`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/answers/post(report_answers_v1_client_reviews_answers_post)`.
    public func report_answers_v1_client_reviews_answers_post(
        headers: Operations.report_answers_v1_client_reviews_answers_post.Input.Headers = .init(),
        body: Operations.report_answers_v1_client_reviews_answers_post.Input.Body
    ) async throws -> Operations.report_answers_v1_client_reviews_answers_post.Output {
        try await report_answers_v1_client_reviews_answers_post(Operations.report_answers_v1_client_reviews_answers_post.Input(
            headers: headers,
            body: body
        ))
    }
    /// 上报一次拼写
    ///
    /// Recorded, never scheduled on.
    ///
    /// 决定 13 keeps spelling out of the scheduler entirely: it is an optional
    /// reinforcement, and letting it move due dates would mix a productive-recall
    /// difficulty into a recognition track. What is stored is what was typed, not
    /// just whether it was right — that is the whole value of the record.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/spelling`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/spelling/post(report_spelling_v1_client_reviews_spelling_post)`.
    public func report_spelling_v1_client_reviews_spelling_post(
        headers: Operations.report_spelling_v1_client_reviews_spelling_post.Input.Headers = .init(),
        body: Operations.report_spelling_v1_client_reviews_spelling_post.Input.Body
    ) async throws -> Operations.report_spelling_v1_client_reviews_spelling_post.Output {
        try await report_spelling_v1_client_reviews_spelling_post(Operations.report_spelling_v1_client_reviews_spelling_post.Input(
            headers: headers,
            body: body
        ))
    }
    /// 批量上报拼写（离线补报用）
    ///
    /// The offline path for spelling, which P4 gave answers and not this.
    ///
    /// 決定 12 of P4 added a batch endpoint for answers because "地铁里每答一题都
    /// 失败" broke 架构前提 2 for half the product. Spelling was out of scope that
    /// day and kept its one-at-a-time online POST, so the last step of the day was
    /// still the one step that needed a network. Same store, same idempotency key,
    /// same per-item verdict as the answers batch — a client that already speaks
    /// that one needs no new vocabulary here.
    ///
    /// **Order does not matter here**, unlike answers: each attempt is an
    /// independent record, and spelling never touches the scheduler (决定 13). They
    /// are applied in the order given anyway, because replaying in sequence is
    /// what the client's outbox does.
    ///
    /// Re-applying an attempt whose first try failed writes a second row in
    /// `spelling_attempts`. That is a duplicate record rather than a wrong one —
    /// nothing reads the table to make a decision — and the alternative is the
    /// attempt being silently dropped.
    ///
    /// - Remark: HTTP `POST /v1/client/reviews/spellings`.
    /// - Remark: Generated from `#/paths//v1/client/reviews/spellings/post(report_spellings_v1_client_reviews_spellings_post)`.
    public func report_spellings_v1_client_reviews_spellings_post(
        headers: Operations.report_spellings_v1_client_reviews_spellings_post.Input.Headers = .init(),
        body: Operations.report_spellings_v1_client_reviews_spellings_post.Input.Body
    ) async throws -> Operations.report_spellings_v1_client_reviews_spellings_post.Output {
        try await report_spellings_v1_client_reviews_spellings_post(Operations.report_spellings_v1_client_reviews_spellings_post.Input(
            headers: headers,
            body: body
        ))
    }
    /// 今日包：当天的文章与复习，一次拿全
    ///
    /// One response the client can work from all day without a network.
    ///
    /// New endpoint rather than fields added to an existing one — 架构铁律 5 lets
    /// us add, never change, and P2 deliberately left this shape unguessed
    /// (`phase-2.html` §6) rather than bolting an invented one onto `/articles`.
    ///
    /// **Does not include exam papers** (决定 9). They have their own entrance at
    /// ``/v1/client/library?source=cet4|cet6|kaoyan``. The response says so in
    /// ``excludes_exam_papers`` so a client cannot conclude otherwise by accident.
    ///
    /// - Remark: HTTP `GET /v1/client/today`.
    /// - Remark: Generated from `#/paths//v1/client/today/get(today_v1_client_today_get)`.
    public func today_v1_client_today_get(headers: Operations.today_v1_client_today_get.Input.Headers = .init()) async throws -> Operations.today_v1_client_today_get.Output {
        try await today_v1_client_today_get(Operations.today_v1_client_today_get.Input(headers: headers))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {}
